// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[username]" | "/auth" | "/be-admin" | "/be-admin/analytics" | "/be-admin/dashboard" | "/be-admin/products" | "/be-admin/settings" | "/be-admin/users" | "/be-admin/users/[id]" | "/dashboard" | "/dashboard/products" | "/dashboard/profile" | "/u/[username]"
type AppRouteHandlerRoutes = "/api/admin/auth/login" | "/api/admin/auth/logout" | "/api/admin/users/[id]/status" | "/api/analytics/track" | "/api/auth/check-username" | "/api/auth/sign-in" | "/api/auth/sign-out" | "/api/auth/sign-up" | "/api/me" | "/api/me/products" | "/api/me/products/[id]" | "/api/me/products/[id]/toggle" | "/api/me/profile" | "/api/public/catalog/[username]"
type PageRoutes = never
type LayoutRoutes = "/" | "/be-admin" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[username]": { "username": string; }
  "/api/admin/auth/login": {}
  "/api/admin/auth/logout": {}
  "/api/admin/users/[id]/status": { "id": string; }
  "/api/analytics/track": {}
  "/api/auth/check-username": {}
  "/api/auth/sign-in": {}
  "/api/auth/sign-out": {}
  "/api/auth/sign-up": {}
  "/api/me": {}
  "/api/me/products": {}
  "/api/me/products/[id]": { "id": string; }
  "/api/me/products/[id]/toggle": { "id": string; }
  "/api/me/profile": {}
  "/api/public/catalog/[username]": { "username": string; }
  "/auth": {}
  "/be-admin": {}
  "/be-admin/analytics": {}
  "/be-admin/dashboard": {}
  "/be-admin/products": {}
  "/be-admin/settings": {}
  "/be-admin/users": {}
  "/be-admin/users/[id]": { "id": string; }
  "/dashboard": {}
  "/dashboard/products": {}
  "/dashboard/profile": {}
  "/u/[username]": { "username": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/be-admin": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
