// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/[username]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[username]">> = Specific
  const handler = {} as typeof import("../../app/[username]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../app/auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/be-admin/(panel)/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/be-admin/analytics">> = Specific
  const handler = {} as typeof import("../../app/be-admin/(panel)/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/be-admin/(panel)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/be-admin/dashboard">> = Specific
  const handler = {} as typeof import("../../app/be-admin/(panel)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/be-admin/(panel)/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/be-admin/products">> = Specific
  const handler = {} as typeof import("../../app/be-admin/(panel)/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/be-admin/(panel)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/be-admin/settings">> = Specific
  const handler = {} as typeof import("../../app/be-admin/(panel)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/be-admin/(panel)/users/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/be-admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../app/be-admin/(panel)/users/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/be-admin/(panel)/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/be-admin/users">> = Specific
  const handler = {} as typeof import("../../app/be-admin/(panel)/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/be-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/be-admin">> = Specific
  const handler = {} as typeof import("../../app/be-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/products">> = Specific
  const handler = {} as typeof import("../../app/dashboard/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/profile">> = Specific
  const handler = {} as typeof import("../../app/dashboard/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/u/[username]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/u/[username]">> = Specific
  const handler = {} as typeof import("../../app/u/[username]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/admin/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/admin/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]/status">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analytics/track/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/track">> = Specific
  const handler = {} as typeof import("../../app/api/analytics/track/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/check-username/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/check-username">> = Specific
  const handler = {} as typeof import("../../app/api/auth/check-username/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/sign-in/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/sign-in">> = Specific
  const handler = {} as typeof import("../../app/api/auth/sign-in/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/sign-out/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/sign-out">> = Specific
  const handler = {} as typeof import("../../app/api/auth/sign-out/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/sign-up/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/sign-up">> = Specific
  const handler = {} as typeof import("../../app/api/auth/sign-up/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/me/products/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/products/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/me/products/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/me/products/[id]/toggle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/products/[id]/toggle">> = Specific
  const handler = {} as typeof import("../../app/api/me/products/[id]/toggle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/me/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/products">> = Specific
  const handler = {} as typeof import("../../app/api/me/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/me/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/profile">> = Specific
  const handler = {} as typeof import("../../app/api/me/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me">> = Specific
  const handler = {} as typeof import("../../app/api/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/catalog/[username]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/catalog/[username]">> = Specific
  const handler = {} as typeof import("../../app/api/public/catalog/[username]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/be-admin/(panel)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/be-admin">> = Specific
  const handler = {} as typeof import("../../app/be-admin/(panel)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
